[build]
    command = "GOOS=linux GOARCH=amd64 go build -o .bin/app cmd/app/main.go"
    functions = "functions"
    publish = "static"

[build.environment]
    GO111MODULE = "on"
[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/gateway/:splat"
    status = 200
[[redirects]]
    from = "/auth/*"
    to = "/.netlify/functions/gateway/:splat"
    status = 200